'''
                                         MSC TECHNOLOGIES
                                  Job Oriented Training with Real Time
                     Mobile: 9148102585, 8121203075         msctechnologies111@gmail.com

'''
#                **** LEARNING TECHNIQUES  ***
    1. NEED TO PREPARE OWN NOTES AFTER COMPLETING EACH TOPIC
    2. EXPLAIN YOUR SELF WHAT YOU UNDERSTOOD 
    3. NEED TO GIVE SESSION AFTER COMPLETING EACH TOPIC

# ACTIVE RECALL (AFTER STUDY RECALL/WRITE WITH OUT SEEING BOOK)
    1. FIRST STUDY
    2. WRITE ON NOTEBOOK WITHOUT SEEING TEXTBOOK

# SIMPLIFY (NEED TO SIMPLIFY TOPIC FOR BETTER UNDERSTANDING AND REMEMBER)
    1. BRAK BIG TOPICS INTO SMALL TOPICS
    2. CREATE END 2 END FLOW
    3. CREATE DIAGRAM AND CHATS

# IMPROVE FOCUS (TO AVOID OVERLOAD FOR BRAIN)
    1. TAKE 5MIN BREAK FOR EVERY 30MIN
    2. TAKE 20 MIN BRAK EVERY 4 HOURS

#REVISION (TO STRENGTHEN MEMORY & AVOID FORGETTING)
    1. REVISE ON SAME DAY AFTER STUDY
    2. REVISE AFTER 1 DAY, 1 WEEK, 1 MONTH (SPACED REPETITION)
    3. MAKE SHORT NOTES/FLASHCARDS FOR QUICK REVISION

# MIX MULTIPLE TOPICS (TO CREATE INTEREST & AVOID BOREDOM)
    1. SPLIT TIME IN A DAY FOR DIFFERENT SUBJECTS
    2. MIX EASY & TOUGH TOPICS TO BALANCE LEARNING
    3. REVISE ONE OLD TOPIC ALONG WITH NEW TOPIC
